POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhYnJpZWwiLCJpZCI6IjYxOTQwNTI4OWMzYTYwNjUwNDVmZTE3YiIsImlhdCI6MTYzNzA5MjgzOSwiZXhwIjoxNjM3MDk2NDM5fQ.itfWiN6YmrXON7TtxXo-4sM5Jop61snrj6VBZWPfDhU

{
    "title": "not missing",
    "url": "http://cubesouls.com",
    "likes": 1000
}